### ISSUE TITLE
Support proxy

### ISSUE THREAD

**Issue by reisenmachtfreude** [azet/tls_tools#2]
Sadly the script does not work through a proxy: Script shows no output.

**Comment by azet** [comment]
@reisenmachtfreude which script are you talking about?

**Comment by reisenmachtfreude** [comment]
@azet sorry, forgot to mention that: check_certificate_chain.py

**Comment by azet** [comment]
I see. Well, that's not really the job of this script. You may find this page useful in general for different proxies and CLI tools: https://wiki.archlinux.org/index.php/proxy_settings

**Comment by ssbarnea** [comment]
I ended up finding this bug while trying to find a tool to dump the SSL certificates while using a proxy. This is specific to the tool because a HTTPS proxy would rewrite the SSL certificates of the final web server. 

Any idea on how to dump these?
